name: Build esptool GUI Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: esptool-gui.exe
          - os: ubuntu-latest
            artifact_name: esptool-gui
          - os: macos-latest
            artifact_name: esptool-gui
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          # Specify the Python version (adjust if needed)
          python_ver: '3.x'
          # Path to your main Python file (or .spec file)
          spec: 'src/esptool-gui.py'
          # Optional: path to your requirements file if you have dependencies
          requirements: 'requirements.txt'
          # PyInstaller options: build one file, assign a name, and hide the console window
          options: '--onefile, --name "esptool-gui", --windowed'
          # Upload the built executable with a custom name per OS
          upload_exe_with_name: ${{ matrix.artifact_name }}
