name: Build ESPTool Simple GUI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: esptool-gui-simple.exe
          - os: ubuntu-latest
            artifact_name: esptool-gui-simple
          - os: macos-latest
            artifact_name: esptool-gui-simple
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install pyinstaller pillow

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --name "ESPTool-Simple-GUI" --windowed --icon "src/espressif_logo.svg" "src/mainw.py"

      - name: Determine executable path
        id: exec_path
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            echo "path=dist/ESPTool-Simple-GUI.exe" >> $GITHUB_OUTPUT
          else
            echo "path=dist/ESPTool-Simple-GUI" >> $GITHUB_OUTPUT
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ steps.exec_path.outputs.path }}
