name: Build esptool GUI Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Adjust if you need a specific Python version

      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          # Build a single executable without a console window (for a GUI app)
          pyinstaller --onefile --noconsole --name esptool-gui src/esptool-gui.py

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: esptool-gui-${{ matrix.os }}
          path: dist/
